USE jiyi_social;

ALTER TABLE `post` ADD COLUMN `images` TEXT COMMENT '图片列表（JSON数组）';
ALTER TABLE `post` ADD COLUMN `location` VARCHAR(100) COMMENT '位置';
ALTER TABLE `post` ADD COLUMN `category` VARCHAR(50) COMMENT '分类';
ALTER TABLE `post` ADD COLUMN `likes_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数';
ALTER TABLE `post` ADD COLUMN `comments_count` INT NOT NULL DEFAULT 0 COMMENT '评论数';
ALTER TABLE `post` ADD COLUMN `shares_count` INT NOT NULL DEFAULT 0 COMMENT '分享数';
ALTER TABLE `post` ADD COLUMN `pinned` TINYINT NOT NULL DEFAULT 0 COMMENT '是否置顶';
